name: Dependency Review

on:
  pull_request:
    branches:
      - main  # Adjust this to match your branch name

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run dependency review
        uses: github/dependency-review-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
